spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
      type:
        descriptor:
          sql: trace

jwt:
  secret: testsecrettestsecrettestsecrettestsecrettestsecret
  expiration:
    access: 1800000
    refresh: 36000000

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
  admin-id: testid
  admin-pw: testpw

meili:
  url: http://localhost:7700
  key: testkey