logging:
  level:
    com.heyticket.backend: DEBUG
  org:
    hibernate:
      type:
        descriptor:
          sql: trace

#  fce47dff5c8040bc906ea1e29823a18a 1번
#  30d5737a4e9e4ba9b1638b74d67507f6 2번
kopis:
  api-key: 30d5737a4e9e4ba9b1638b74d67507f6
  performance:
    url: http://kopis.or.kr/openApi/restful
    token: c48ac57fdf5347408aa0eb10d029dd12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://heyticket-db.c8ycq7qrciya.ap-northeast-2.rds.amazonaws.com:3306/heyticket?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: heyhey123!

  jpa:
    hibernate:
      ddl-auto: update
      type:
        descriptor:
          sql: trace

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblkcfPQye08f7MGVA9XkHa
  expiration:
    access: 300000 # 임시로 5분 10800000 = 3 * 60 * 60 * 100 3시간
    refresh: 36000000 # 36000000 = 10 * 60 * 60 * 100 10시간

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
  admin-id: heyticket.cs@gmail.com
  admin-pw: mamsymqzixfeltug